apps/ingredients/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from apps.ingredients.views import IngredientListView, SpiritDetailView, MixerDetailView, SpiritCreateView
from apps.ingredients.views import MixerCreateView, IngredientCreateView, IngredientDeleteView

urlpatterns = patterns('',
    url(r'^$', IngredientListView.as_view(), name='ingredient_list'),
    url(r'^spirit/create/$', SpiritCreateView.as_view(), name='spirit_create'),
    url(r'^mixer/create/$', MixerCreateView.as_view(), name='mixer_create'),
    url(r'^spirit/(?P<slug>.+)/$', SpiritDetailView.as_view(), name='spirit_detail'),
    url(r'^mixer/(?P<slug>.+)/$', MixerDetailView.as_view(), name='mixer_detail'),
    url(r'^(?P<slug>[-\w]+)/add_(?P<type>[-\w]+)/$', IngredientCreateView.as_view(), name='ingredient_create'),
    url(r'^(?P<slug>[-\w]+)/remove_ingredient/(?P<pk>\d+)/$', IngredientDeleteView.as_view(), name='ingredient_delete'),
)

mixees/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt

from schema import schema
from graphene.contrib.django.views import GraphQLView

from apps.core.views import VueTemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mixees.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'', include('apps.home.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cocktails/', include('apps.cocktails.urls')),
    url(r'^ingredients/', include('apps.ingredients.urls')),
    url(r'^tastes/', include('apps.tastes.urls')),
    url(r'^users/', include('apps.users.urls')),

    url(r'^graphql', csrf_exempt(GraphQLView.as_view(schema=schema))),
    url(r'^graphiql', include('django_graphiql.urls')),

    url(r'^vue', VueTemplateView.as_view()),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

apps/ingredients/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from django.template.defaultfilters import slugify
# from django.contrib.contenttypes import generic
# from django.contrib.contenttypes.models import ContentType

from apps.cocktails.models import Cocktail


class Liquid(models.Model):
    """Base class for Spirit and Mixer"""
    name = models.CharField(max_length=20, unique=True)
    slug = models.CharField(max_length=20, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Liquid, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Spirit(Liquid):
    volume = models.PositiveSmallIntegerField(null=True, validators=[MaxValueValidator(100)])

    class Meta:
        verbose_name = "Spirit"
        verbose_name_plural = "Spirits"

    @property
    def volume_display(self):
        return "%g%%" % self.volume

    @models.permalink
    def get_absolute_url(self):
        return ('spirit_detail', [self.slug])


class Mixer(Liquid):
    class Meta:
        verbose_name = "Mixer"
        verbose_name_plural = "Mixers"

    @models.permalink
    def get_absolute_url(self):
        return ('mixer_detail', [self.slug])


class Ingredient(models.Model):
    """Ingredient class is the join for Cocktails and Liquids"""
    cocktail = models.ForeignKey(Cocktail)
    amount = models.DecimalField(decimal_places=2, max_digits=5, null=True)
    measurement = models.CharField(default='Some', max_length=30)
    spirit = models.ForeignKey(Spirit, blank=True, null=True)
    mixer = models.ForeignKey(Mixer, blank=True, null=True)

    class Meta:
        verbose_name = "Ingredient"
        verbose_name_plural = "Ingredients"

    def save(self, *args, **kwargs):
        if self.spirit:
            self.cocktail.total_parts += self.amount
            self.cocktail.save()

        super(Ingredient, self).save(*args, **kwargs)

    def __str__(self):
        if self.amount:
            return "%g %s" % (self.amount, self.measurement)
        else:
            return self.measurement

apps/ingredients/forms.py
from django.forms import ModelForm
from apps.ingredients.models import Ingredient


class IngredientCreateForm(ModelForm):
    class Meta:
        model = Ingredient
        fields = ['amount', 'measurement', 'spirit', 'mixer']

apps/ingredients/views.py
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
)
from django.core.urlresolvers import reverse
from django.forms import HiddenInput

from apps.core.mixins import LoginRequiredMixin
from apps.ingredients.models import Spirit, Mixer, Ingredient
from apps.cocktails.models import Cocktail
from apps.ingredients.forms import IngredientCreateForm


class IngredientListView(TemplateView):
    template_name = 'ingredients/ingredient_list.html'

    def get_context_data(self, **kwargs):
        context = super(IngredientListView, self).get_context_data(**kwargs)
        context['spirits'] = Spirit.objects.all()
        context['mixers'] = Mixer.objects.all()
        return context


class SpiritDetailView(DetailView):
    model = Spirit


class MixerDetailView(DetailView):
    model = Mixer


class SpiritCreateView(LoginRequiredMixin, CreateView):
    model = Spirit
    fields = ['name', 'volume']


class MixerCreateView(LoginRequiredMixin, CreateView):
    model = Mixer
    fields = ['name']


class IngredientCreateView(LoginRequiredMixin, CreateView):
    model = Ingredient
    form_class = IngredientCreateForm

    def get_form(self, form_class):
        form = super(IngredientCreateView, self).get_form(form_class)
        form.instance.cocktail = Cocktail.objects.get(slug=self.kwargs['slug'])

        if self.kwargs['type'] == 'spirit':
            form.fields['mixer'].widget = HiddenInput()
        elif self.kwargs['type'] == 'mixer':
            form.fields['spirit'].widget = HiddenInput()

        return form

    def get_context_data(self, **kwargs):
        context = super(IngredientCreateView, self).get_context_data(**kwargs)
        context['ingredient_type'] = self.kwargs['type']
        return context

    def get_success_url(self):
        if '_addspirit' in self.request.POST:
            return reverse(
                'ingredient_create',
                kwargs={
                    'slug': self.kwargs['slug'],
                    'type': 'spirit'
                }
            )
        elif '_addmixer' in self.request.POST:
            return reverse(
                'ingredient_create',
                kwargs={
                    'slug': self.kwargs['slug'],
                    'type': 'mixer'
                }
            )
        return reverse('cocktail_detail', kwargs={'slug': self.kwargs['slug']})


class IngredientDeleteView(DeleteView):
    model = Ingredient
    template_name = "ingredients/ingredient_confirm_delete.html"

    def get_success_url(self):
        return reverse('cocktail_detail', args=[self.kwargs['slug']])

templates/ingredients/ingredient_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete ingredient{% endblock %}

{% block content %}
	<h1>Delete ingredient</h1>

	<h2>Really delete {{ object }} from {{ object.cocktail }}?</h2>

	<p>It will be permanently lost</p>

	<form method="post">{% csrf_token %}
    	<button type="submit" class="btn btn-danger">Delete</button>
	</form>
	</br>
	<button class="btn btn-default"><a href="{% url "cocktail_detail" object.cocktail.slug %}">Cancel</a></button>

{% endblock %}

templates/ingredients/ingredient_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add {{ ingredient_type }}{% endblock %}

{% block content %}
	
	<h1>Already added {{ ingredient_type }}s</h1>

	<ul>
		{% if form.instance.cocktail.ingredient_set.all %}
			{% for ingredient in form.instance.cocktail.ingredient_set.all %}
				<li>{{ ingredient }}</li>
		    {% endfor %}
		{% else %}
			<p>None</p>
		{% endif %}
	</ul>

	<h1>Add {{ ingredient_type }}</h1>

	<form method="post">
	    {% csrf_token %}
	    {{ form|crispy }}
	    <button type="submit" class="btn btn-primary" name="save">Save</button>
	    <button type="submit" class="btn btn-primary" name="_addspirit">Save and add a spirit</button>
	    <button type="submit" class="btn btn-primary" name="_addmixer">Save and add a mixer</button>
	</form>
	</br>
	<p><a href="{% url 'cocktail_detail' form.instance.cocktail.slug %}">Back to Cocktail</a></p>
{% endblock %}

templates/ingredients/ingredient_list.html
{% extends "base.html" %}

{% block title %}Ingredients{% endblock %}

{% block content %}
	<h1>Ingredients</h1>
	<h2>Spirits</h2>
	<ul>
		{% for spirit in spirits %}
			<li><a href="{% url 'spirit_detail' spirit.slug %}">{{ spirit }}</a></li>
		{% endfor %}
	</ul>
	<h2>Mixers</h2>
	<ul>
		{% for mixer in mixers %}
			<li><a href="{% url 'mixer_detail' mixer.slug %}">{{ mixer }}</a></li>
		{% endfor %}
	</ul>
	{% if user.is_authenticated %}
		<a href="{% url 'spirit_create' %}">Add Spirit</a>
		</br>
		<a href="{% url 'mixer_create' %}">Add Mixer</a>
	{% else %}
		<p><a href="{% url 'users.register' %}">Register</a> or <a href="{% url 'users.login' %}?next={{ request.path }}">Login</a> to add new ingredients.</p>
    {% endif %}
{% endblock %}

templates/ingredients/mixer_detail.html
{% extends "base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
	<h1>{{ object }}</h1>
	<a href="{% url "ingredient_list" %}">Back to ingredient list</a>
{% endblock %}
	

templates/ingredients/mixer_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Mixer{% endblock %}

{% block content %}
<h1>Add Mixer</h1>

<form method="POST">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-prymary" type="submit">Save</button>
</form>
<a href="{% url "ingredient_list" %}">Back to ingredient list</a>
{% endblock %}

templates/ingredients/mixeringredient_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Mixer{% endblock %}

{% block content %}
	
	<h1>Already added Mixers</h1>

	<ul>
		{% for ingredient in form.instance.cocktail.mixeringredient_set.all %}
			<li>{{ ingredient }}</li>
	    {% endfor %}
	</ul>

	<h1>Add Mixer</h1>

	<form method="post">
	    {% csrf_token %}
	    {{ form|crispy }}
	    <button type="submit" class="btn btn-primary" name="save">Save</button>
	    <button type="submit" class="btn btn-primary" name="_addspirit">Save and add a spirit</button>
	    <button type="submit" class="btn btn-primary" name="_addmixer">Save and add a mixer</button>
	</form>
	</br>
	<p><a href="{% url "cocktail_detail" form.instance.cocktail.slug %}">Back to Cocktail</a></p>
{% endblock %}

templates/ingredients/spirit_detail.html
{% extends "base.html" %}

{% block title %}{{ object }}{% endblock %}

{% block content %}
	<h1>{{ object }}</h1>
    <p>Volume: {{ object.volume_display }}</p>
	<a href="{% url 'ingredient_list' %}">Back to ingredient list</a>
{% endblock %}

templates/ingredients/spirit_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Spirit{% endblock %}

{% block content %}
<h1>Add Spirit</h1>

<form method="POST">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-prymary" type="submit">Save</button>
</form>
<a href="{% url "ingredient_list" %}">Back to ingredient list</a>
{% endblock %}